server:
  port: 8099

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  data:
    mongodb:
      uri: mongodb://localhost:27017/city
